# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fured', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('author_contry', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=50)),
                ('book_image_path', models.CharField(max_length=100)),
                ('book_download_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'book_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=50)),
                ('comment_email', models.CharField(max_length=50)),
                ('comment_message', models.CharField(max_length=500)),
                ('create_at', models.FloatField()),
            ],
            options={
                'db_table': 'comment_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayMusicTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('songer_name', models.CharField(max_length=50)),
                ('song_image_path', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'play_music_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendMusicTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('song_type', models.CharField(max_length=50)),
                ('recommend_name', models.CharField(max_length=50)),
                ('recommend_reason', models.CharField(max_length=500)),
                ('create_at', models.FloatField()),
            ],
            options={
                'db_table': 'recommend_music_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareMoiveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moive_name', models.CharField(max_length=50)),
                ('share_reason', models.CharField(max_length=500)),
                ('moive_download_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'share_moive_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
